### ISSUE TITLE
Suggestion: add this function since it was in FastBitBuffer docs but not in the actual module

### ISSUE THREAD

**Issue by kanjiman** [rstk/bitbuffer#3]
`function BitBuffer.BitsRequired(Value: number)
	return math.ceil(math.log(Value,2))
end`

Just a neat function that returns how many bits is a number, which was also in FastBitBuffer docs but never in the actual module.

![hm](https://user-images.githubusercontent.com/60044029/171060976-07b61f08-9798-46f9-baf1-29b63eb1d9e0.png)

**Comment by rstk** [comment]
I don't think this belongs in the library. I'd prefer to keep the library as minimal as possible, so adding niche features like this doesn't seem appropriate. If you need this function, you can just add it to your scripts.
